---
- simulation_meta: 
  log_directory: C:/Users/kdwn/projects/propagate/log/
- solver:
  integration_scheme: rk4
  timestep: 0.01
  start_time: 0.0
  end_time: 120.0
  channel_names:
    - sigma_0
    - sigma_1
    - sigma_2
    - omega_0
    - omega_1
    - omega_2
  states_are_angles: [false, false, false, true, true, true]
  angles_are_deg: true
  initial_states:
    - 0.3
    - -0.4
    - 0.5 
    - 1.0
    - 1.75
    - -2.2
  state_ndim : 6
  control_in_lockstep: true
  control_update_rate: 100
- system:
  plant_model: attitude_kinematics_mrp
  actuator_model: direct
  inertia: [
    10., 0., 0.,
     0., 5., 0.,
     0., 0., 7.5
  ]
- control:
  scheme: simple_pd
  gain:
    - proportional: 5.
    - derivative: 10.
    - integral: .01
  integral_term: false
  reference_state: orbit
... 